resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - redis-master-deployment.yaml
  - redis-master-service.yaml
  - redis-replica-deployment.yaml
  - redis-replica-service.yaml
  - redis-follower-service.yaml
